package ops

import (
	"github.com/techmuch/dialogmapper/internal/ibis"
	"github.com/techmuch/dialogmapper/internal/store"
)

// Schema describes the op contract in the same spirit as `grammar --json`:
// generated from the code rather than restated in prose, so it cannot drift.
//
// An agent that reads this and `grammar --json` has everything it needs to
// mutate a map correctly without guessing — which is the whole reason raw SQL
// looked like the only option.
func Schema() map[string]any {
	fields := map[string][]string{
		CreateMap:  {"name (required)", "description"},
		DeleteMap:  {"map (name or id; undoable)"},
		CreateNode: {"map", "type (required)", "title (required)", "body", "tags", "links", "status", "parent", "rel"},
		UpdateNode: {"id (required)", "title", "body", "tags", "links", "status", "type"},
		DeleteNode: {"id (required; removes it from every map)"},
		RemoveNode: {"id (required)", "map (removes it from this map only)"},
		CreateEdge: {"map", "from (required)", "to (required)", "rel (inferred when omitted)"},
		DeleteEdge: {"id (required)"},
	}
	notes := map[string]string{
		CreateNode: "parent + rel attach the new node in the same transaction, exactly as the canvas does. Omit rel to let the IBIS grammar infer the obvious relationship.",
		DeleteNode: "Nodes are shared, so this destroys it on every map. Use remove_node to take it off one map only.",
		DeleteMap:  "Nodes survive: a map is a view, and deleting it never destroys shared thinking.",
		CreateEdge: "Edges point child to parent: a Pro supports an Idea, so from=pro, to=idea.",
	}

	ops := make([]map[string]any, 0, len(Kinds))
	for _, k := range Kinds {
		entry := map[string]any{"op": k, "fields": fields[k]}
		if n, ok := notes[k]; ok {
			entry["note"] = n
		}
		ops = append(ops, entry)
	}

	types := make([]string, 0, len(ibis.NodeTypes))
	for _, t := range ibis.NodeTypes {
		types = append(types, string(t))
	}
	rels := make([]string, 0, len(ibis.Relationships))
	for _, r := range ibis.Relationships {
		rels = append(rels, string(r))
	}

	return map[string]any{
		"input": "a JSON array of operations on stdin; a single object is accepted too",
		"ops":   ops,
		"values": map[string]any{
			"nodeTypes":     types,
			"relationships": rels,
			"statuses": []store.Status{
				store.StatusOpen, store.StatusResolved, store.StatusRejected, store.StatusParked,
			},
			"links": "array of {\"url\": \"...\", \"title\": \"...\"} — not plain strings",
		},
		"guarantees": []string{
			"Every operation is checked against the IBIS grammar; illegal edges are refused with an explanation.",
			"Every operation except create_map is journaled, so `dialogmapper undo` reverses it. The report says how many of a batch are reversible.",
			"Ids are generated by dialogmapper; never invent one.",
			"map may be a name or an id, and may be omitted when the project has exactly one map.",
		},
		"caveats": []string{
			"A batch is not one transaction. Operations apply in order and stop at the first failure; the report says how many were applied and how to undo them.",
			"Run with --dry-run to validate without writing.",
		},
		"grammar": "run `dialogmapper grammar --json` for which relationships are legal between which node types",
	}
}
